BULLETTRAIN_CUSTOM_MSG="\`kcc\`"
BULLETTRAIN_CUSTOM_FG=black
BULLETTRAIN_CUSTOM_BG=blue
BULLETTRAIN_DIR_EXTENDED=0
BULLETTRAIN_PROMPT_SEPARATE_LINE=false
BULLETTRAIN_PROMPT_CHAR=""
BULLETTRAIN_PROMPT_ORDER=(status custom nvm dir git)
